<?php
/**
 * This class covers all functions for displaying the
 * backgrounds for posts created by wordpress.
 *
 * @author InoPlugs | Peter Schoenmann
 * @version 1.1.0.0
 *
 */
class inoplugs_background_display
{
	protected $bg_image;
	protected $ino_bglite_options;

	public function __construct()
	{
		global $ino_bglite_options;
		$this->bg_image = "";
		$this->ino_bglite_options = $ino_bglite_options;
	}

	public function __destruct()
	{
		unset($this->bg_image);
		unset($this->ino_bglite_options);
	}

	/**
	 * frontend includes
	 */
	public function handler_frontend_includes()
	{
		$ino_backgrounds_path = INO_WPBLITE_URLPATH.'includes/';
		wp_enqueue_script('jquery');

		if(!is_admin())
		{
			wp_register_style('inoplugs_backgrounds_css', $ino_backgrounds_path.'wp-backgrounds.css');
			wp_enqueue_style('inoplugs_backgrounds_css');
		}
    }

	/**
	 *	Background image function
	 *
	 * @return <type>
	 */
	public function handler_add_background_slideshow()
	{
		if (is_admin())
		{
			return;
		}
		$images_slideshow = $this->set_bg_images();

		$background_slideshow = '';
		$background_slideshow .= "\n\n\n<!--\n\n";
		$background_slideshow .="###############################################################################\n";
		$background_slideshow .="#                      Fullscreen Backgrounds generated by                    #\n";
		$background_slideshow .="#       WP-Backgrounds Lite Plugin by InoPlugs (http://inoplugs.com)          #\n";
		$background_slideshow .="###############################################################################\n";
		$background_slideshow .="\n-->\n";


		/*if ($this->deactivate == "1")
		{
			add_action('wp_footer', array(&$this, 'handler_set_fallback_image'));
			return;
		}*/

		$ino_backgrounds_path = WP_PLUGIN_URL.'/wp-backgrounds-lite/includes/';

		$background_slideshow .= "<script type='text/javascript' src='".$ino_backgrounds_path."wp-backgrounds.js'></script>\n";

		$background_slideshow .= "<style type=\"text/css\">\n";

		if ( !empty($this->ino_bglite_options['zindex']) )
		{
			$background_slideshow .= '#supersized{z-index:'.$this->ino_bglite_options['zindex'].' !important;} ';
		}
		else
		{
			$background_slideshow .= '#supersized{z-index: 0 !important;} ';
		}

		if ( !empty($this->ino_bglite_options['bg_color']) )
		{
			$background_slideshow .= 'body{background-color:'.$this->ino_bglite_options['bg_color'].' !important;} ';
		}

		if ( !empty($this->ino_bglite_options['containerid']) )
		{
			$container = '';
			$container .= $this->ino_bglite_options['containerid'].'{';

			if ( !empty($this->ino_bglite_options['zindexcontainer']) )
			{
				$container .= 'z-index:'.$this->ino_bglite_options['zindexcontainer'].';';
			}

			if ( !empty($this->ino_bglite_options['positioncontainer']) )
			{
				$container .= 'position:'.$this->ino_bglite_options['positioncontainer'].';';
			}

			$container .= '} ';

			$background_slideshow .= $container;
		}


		$background_slideshow .= "\n</style>\n";
		$background_slideshow .= "\n<script type='text/javascript'>\n";
		$background_slideshow .= '
			jQuery(document).ready(function() {
				jQuery(function($){
					$.supersized({';

		$background_slideshow .= "\n".$images_slideshow;

		$background_slideshow .= "\n}); \n }); \n });";
		$background_slideshow .= "\n</script>\n";
		$background_slideshow .= "\n<!-- end of function - WP-Backgrounds by InoPlugs -->\n\n\n";


		/* check if we got any slides - if not don't output bg function */
		add_action('wp_footer', array(&$this, 'handler_set_fallback_image'));
		if (!$images_slideshow == false){
			echo $background_slideshow;
		}else{
			return;
		}
	}


	public function handler_set_fallback_image()
	{
		$inoplugs = apply_filters("inoplugs_link", '<div style="display: none;"><a href="http://inoplugs.com">WP-Backgrounds Lite by InoPlugs Web Design</a> and <a href="http://schoenmann.at/">Juwelier Sch&ouml;nmann 1010 Wien</a></div>');
		echo $inoplugs;
	}

	protected function set_bg_images()
	{
		global $wp_query, $post;

		if(!empty($wp_query->post->ID))
		{
			$get_external_bg_image = get_post_meta($wp_query->post->ID, 'upload_image', true);
			$get_image_link = get_post_meta($wp_query->post->ID, 'image_url', true);
		}

		if (empty($get_external_bg_image)) {
			$deactivate_image = 'on';
			return;
		}
		else
		{
			if (is_single() || is_page())
			{
				$this->bg_image = $get_external_bg_image;
			}
		}

		if(!empty($this->bg_image))
		{
			if (!empty($get_image_link))
			{
				$url = ", url : '$get_image_link'";
			}
			else
			{
				$url = '';
			}
			$background_image = '';
			$background_image .= "{image : '{$this->bg_image}' $url }";
			$background_image = 'slides : [ '.$background_image.' ]';
			return $background_image;
		}
		else
		{
			return $background_image = false;
		}
	}
}
?>
